---
- name: Restart Docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
  become: yes

- name: Restart Jenkins
  ansible.builtin.systemd:
    name: jenkins
    state: restarted
  become: yes

