apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  APP_ENV: {{ .Values.configmap.APP_ENV | quote }}
  APP_VERSION: {{ .Values.configmap.APP_VERSION | quote }}
  APP_NAME: {{ .Values.configmap.APP_NAME | quote }}
  LOG_LEVEL: {{ .Values.configmap.LOG_LEVEL | quote }}
  MAX_CONNECTIONS: {{ .Values.configmap.MAX_CONNECTIONS | quote }}

