terraform {
  required_version = ">= 1.0"

  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }
  }
}

# Create output directory
resource "local_file" "output_dir_placeholder" {
  content  = "# Terraform managed output directory\n"
  filename = "${var.output_dir}/.terraform-managed"
}

# Create hosts mapping file
resource "local_file" "hosts_mapping" {
  content  = <<-HOSTS
    # Terraform managed hosts mapping
    # Generated by: ${var.app_name} - ${var.environment}
    # Do not edit manually

    ${var.minikube_ip}  ${var.host_entry}
  HOSTS
  filename = "${var.output_dir}/hosts-mapping.txt"
}

# Create app config file
resource "local_file" "app_config" {
  content  = <<-CONFIG
    # App Configuration
    # Generated by Terraform for ${var.environment} environment
    # App: ${var.app_name}

    APP_NAME=${var.app_name}
    APP_ENV=${var.environment}
    APP_PORT=${var.app_port}

    # Database config
    DB_HOST=${var.db_host}
    DB_NAME=${var.db_name}
    DB_USER=${var.db_user}

    # Network config
    APP_HOST=${var.host_entry}
    APP_URL=http://${var.host_entry}
  CONFIG
  filename = "${var.output_dir}/app.env"
}

# Create a deployment info file
resource "local_file" "deployment_info" {
  content  = <<-INFO
    # Deployment Info
    # Managed by Terraform

    RELEASE_NAME=${var.app_name}-${var.environment}
    NAMESPACE=${var.environment}
    IMAGE_NAME=${var.app_name}
    MINIKUBE_IP=${var.minikube_ip}
    HOST_ENTRY=${var.host_entry}
    APP_URL=http://${var.host_entry}
  INFO
  filename = "${var.output_dir}/deployment-info.txt"
}

