apiVersion: v1
data:
  DB_HOST: bXlzcWw=
  DB_NAME: dHJhaW5pbmdkYg==
  DB_PASSWORD: U3Ryb25nUGFzc3dvcmQxMjMh
  DB_PORT: MzMwNg==
  DB_USER: dHJhaW5pbmdhcHA=
kind: Secret
metadata:
  creationTimestamp: "2026-04-15T09:58:38Z"
  name: training-site-secrets
  namespace: dev
  resourceVersion: "918"
  uid: d632e131-35f2-4416-8726-1792fbe5167b
type: Opaque
