apiVersion: v1
data:
  DB_HOST: bXlzcWw=
  DB_NAME: dHJhaW5pbmdkYg==
  DB_PASSWORD: U3Ryb25nUGFzc3dvcmQxMjMh
  DB_PORT: MzMwNg==
  DB_USER: dHJhaW5pbmdhcHA=
kind: Secret
metadata:
  name: training-site-secrets
  namespace: dev

type: Opaque
